insert into slideshow values(1,'Interesting Pictures', NOW());
    insert into slides values(1,1,1,1); 
    insert into slides values(2,2,2,1); 
    insert into slides values(3,3,3,1); 
    insert into slides values(4,4,4,1); 
    insert into slides values(5,5,5,1); 
    insert into slides values(6,6,6,1); 
    insert into slides values(7,7,7,1); 
    insert into slides values(8,8,8,1); 
    insert into slides values(9,9,9,1); 
    insert into photos values(1,'balboa_park.jpg'); 
    insert into photos values(2,'camel.jpg'); 
    insert into photos values(3,'cat_and_candles.jpg'); 
    insert into photos values(4,'hut.jpg'); 
    insert into photos values(5,'mosaic.jpg'); 
    insert into photos values(6,'polar_bear.jpg'); 
    insert into photos values(7,'police.jpg'); 
    insert into photos values(8,'sleeping_dog.pg'); 
    insert into photos values(9,'stairs.jpg');
insert into categories values(1, 'All', null); 
insert into categories values(2, 'People', 1); 
insert into categories values(3, 'Animals', 1); 
insert into categories values(4, 'Places', 1); 
insert into categories values(5, 'Things', 1); 
insert into categories values(6, 'Friends', 2);
insert into categories values(7, 'Family', 2); 
    insert into categories_photos values(4,1);
    insert into categories_photos values(3,2); 
    insert into categories_photos values(3,3); 
    insert into categories_photos values(4,4); 
    insert into categories_photos values(5,5); 
    insert into categories_photos values(3,6); 
    insert into categories_photos values(2,7); 
    insert into categories_photos values(4,8); 
    insert into categories_photos values(4,9); 
    insert into categories_photos values(4,7);                                                        
